
title: Shan He's Homepage
page-top-title: Shan He (何山)
top-section-bg-text: An LLM Designer and Efficient Machine Learning System Nerd
home-subtitle: Shan He&ensp;|&ensp;何山
copyright-text: '&copy; Congrui Yin 2023. All Rights Reserved.'
