
title: Shan He's Homepage
page-top-title: Shan He (何山)
top-section-bg-text: An aspiring LLM architect and avid machine learning systems enthusiast
home-subtitle: Shan He&ensp;|&ensp;何山
copyright-text: '&copy; Shan He 2024. All Rights Reserved.'
