
title: Congrui Yin's Homepage
page-top-title: Congrui Yin (殷骢睿)
top-section-bg-text: An LLM Designer and Efficient Machine Learning System Nerd
home-subtitle: Congrui Yin&ensp;|&ensp;殷骢睿
copyright-text: '&copy; Congrui Yin 2023. All Rights Reserved.'
